// This file is used for development when building directly in Xcode.
// The actual Version.swift is auto-generated by the build script.
// To use this file for development, copy it to Version.swift:
// cp Version.swift.development Version.swift

struct Version {
    static let current = "dev"
}