#!/bin/bash
# Commands to run the Poltergeist migration

echo "🚀 Running Poltergeist Migration"
echo "================================"
echo ""
echo "Run these commands in your terminal:"
echo ""
echo "# 1. Navigate to Poltergeist directory"
echo "cd ../poltergeist"
echo ""
echo "# 2. Run the migration script"
echo "./scripts/migrate-to-generic-targets.sh"
echo ""
echo "# 3. Build the TypeScript code"
echo "npm run build"
echo ""
echo "# 4. Run tests to verify"
echo "npm test"
echo ""
echo "# 5. Test with Peekaboo's config"
echo "cd ../Peekaboo"
echo "npm run poltergeist:status"
echo ""
echo "# 6. If everything works, commit in Poltergeist repo"
echo "cd ../poltergeist"
echo "git add -A"
echo "git commit -m 'feat: Implement generic target system'"
echo ""
echo "# 7. Update package version (major bump due to breaking change)"
echo "npm version major"
echo ""
echo "# 8. Publish to npm (when ready)"
echo "npm publish"