// This file is auto-generated by the build script. Do not edit manually.
enum Version {
    static let current = "Peekaboo 3.0.0"
    static let gitCommit = "f24f380f-dirty"
    static let gitCommitDate = "2025-11-10 16:27:08 +0000"
    static let gitBranch = "main"
    static let buildDate = "2025-11-10T16:39:04+00:00"
    
    static var fullVersion: String {
        return "\(current) (\(gitBranch)/\(gitCommit), built: \(buildDate))"
    }
}
