// This file is auto-generated by the build script. Do not edit manually.
enum Version {
    static let current = "Peekaboo 3.0.0"
    static let gitCommit = "843d404a-dirty"
    static let gitCommitDate = "2025-11-10 18:08:29 +0000"
    static let gitBranch = "main"
    static let buildDate = "2025-11-10T18:44:46+00:00"
    
    static var fullVersion: String {
        return "\(current) (\(gitBranch)/\(gitCommit), built: \(buildDate))"
    }
}
