// This file is auto-generated by the build script. Do not edit manually.
enum Version {
    static let current = "Peekaboo 3.0.0"
    static let gitCommit = "4a9b98c0-dirty"
    static let gitCommitDate = "2025-11-12 11:15:21 +0000"
    static let gitBranch = "main"
    static let buildDate = "2025-11-12T11:15:23+00:00"
    
    static var fullVersion: String {
        return "\(current) (\(gitBranch)/\(gitCommit), built: \(buildDate))"
    }
}
