// This file is auto-generated by the build script. Do not edit manually.
enum Version {
    static let current = "Peekaboo 3.0.0"
    static let gitCommit = "47568e73-dirty"
    static let gitCommitDate = "2025-11-14 07:27:37 +0000"
    static let gitBranch = "main"
    static let buildDate = "2025-11-14T09:06:29+00:00"

    static var fullVersion: String {
        "\(current) (\(gitBranch)/\(gitCommit), built: \(buildDate))"
    }
}
