// This file is auto-generated by the build script. Do not edit manually.
enum Version {
    static let current = "Peekaboo 3.0.0"
    static let gitCommit = "68bc2a21-dirty"
    static let gitCommitDate = "2025-11-12 18:11:23 +0000"
    static let gitBranch = "main"
    static let buildDate = "2025-11-12T23:36:26+00:00"

    static var fullVersion: String {
        "\(current) (\(gitBranch)/\(gitCommit), built: \(buildDate))"
    }
}
