/// This file is auto-generated by the build script. Do not edit manually.
enum Version {
    static let current = "Peekaboo 3.1.0"
    static let gitCommit = "29b698da"
    static let gitCommitDate = "2026-05-10 18:56:56 +0100"
    static let gitBranch = "main"
    static let buildDate = "2026-05-10T18:58:00+01:00"

    static var fullVersion: String {
        "\(current) (\(gitBranch)/\(gitCommit), built: \(buildDate))"
    }
}
