# SwiftLint configuration for Peekaboo CLI (Swift 6.2)
#
# The CLI target runs in Swift 6.2 strict concurrency mode, so we rely on SwiftFormat
# to insert explicit `self` where required and keep opt-in rules focused on logic bugs
# instead of style that SwiftFormat already enforces.
swiftlint_version: 0.62.2

# Rules
disabled_rules:
  - trailing_whitespace
  - trailing_comma # SwiftFormat handles trailing commas for us
  - todo
  - superfluous_disable_command
  - function_parameter_count
  - function_body_length
  - type_body_length
  - file_length
  - cyclomatic_complexity
  - nesting
  - large_tuple
  - line_length
  - identifier_name
  - force_cast
  - void_return
  - empty_string
  - unused_optional_binding
  - unused_enumerated
  - for_where

opt_in_rules:
  - closure_spacing
  - empty_count
  - empty_string
  - contains_over_filter_count
  - contains_over_filter_is_empty
  - contains_over_first_not_nil
  - contains_over_range_nil_comparison
  - discouraged_object_literal
  - first_where
  - last_where
  - legacy_multiple
  - prefer_self_type_over_type_of_self
  - sorted_first_last
  - unneeded_parentheses_in_closure_argument
  - vertical_parameter_alignment_on_call

# Rule configurations tuned for Swift 6.2 ergonomics
# Paths
included:
  - Sources
  - Tests

excluded:
  - .build
  - .swiftpm
  - .git
  - Package.swift
  - DerivedData
  - "**/.build"
  - "**/DerivedData"
